# Generated by Django 4.1.1 on 2022-10-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_likes_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='follower',
            field=models.CharField(max_length=524),
        ),
    ]
