# Generated by Django 4.1.1 on 2022-10-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_followers_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='like',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
