# Generated by Django 4.1.1 on 2022-10-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_posts_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='like',
            field=models.IntegerField(),
        ),
    ]
